spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd #设置日期形式
#  #配置数据源
#  datasource:
#    username: root
#    password: 123
#    url: jdbc:mysql://localhost:3306/books?serverTimezone=UTC&useUnicode=ture&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: druid
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 1
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0


  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis

## Mybatis 配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml #mapper xml 文件地址
  type-aliases-package: com.qimozuoye.pojo #实体类包路径
server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  check-config-location: false
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.qimozuoye.pojo

